import { Component, Input, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { RoomCard } from '../../core/models/room-card.model';
import { CurrencyCompactPipe } from '../pipes/currency-compact.pipe';

@Component({
  selector: 'app-room-card',
  imports: [CommonModule, CurrencyCompactPipe],
  template: `
    <article data-testid="room-card"
      class="bg-white rounded-xl shadow-sm hover:shadow-lg transition-all duration-300 overflow-hidden cursor-pointer group border border-gray-100"
      (click)="navigateToDetail()"
      role="button"
      tabindex="0"
      (keydown.enter)="navigateToDetail()"
      (keydown.space)="$event.preventDefault(); navigateToDetail()"
      [attr.aria-label]="'View details for ' + getAutoGeneratedTitle()"
    >
      <!-- Image with Badges -->
      <div class="relative aspect-[4/3] overflow-hidden">
        <img
          [src]="room.image"
          [alt]="getAutoGeneratedTitle()"
          class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
          loading="lazy" decoding="async" fetchpriority="low"
          (load)="onImgLoad()"
          [class.img-loading]="imgLoading"
        >
        
        <!-- Top Left: Verified Badge -->
        <div class="absolute top-3 left-3">
          <span class="px-2.5 py-1 text-xs font-semibold bg-blue-500 text-white rounded-full flex items-center gap-1 shadow-md">
            <svg class="w-3 h-3" fill="currentColor" viewBox="0 0 20 20">
              <path fill-rule="evenodd" d="M6.267 3.455a3.066 3.066 0 001.745-.723 3.066 3.066 0 013.976 0 3.066 3.066 0 001.745.723 3.066 3.066 0 012.812 2.812c.051.643.304 1.254.723 1.745a3.066 3.066 0 010 3.976 3.066 3.066 0 00-.723 1.745 3.066 3.066 0 01-2.812 2.812 3.066 3.066 0 00-1.745.723 3.066 3.066 0 01-3.976 0 3.066 3.066 0 00-1.745-.723 3.066 3.066 0 01-2.812-2.812 3.066 3.066 0 00-.723-1.745 3.066 3.066 0 010-3.976 3.066 3.066 0 00.723-1.745 3.066 3.066 0 012.812-2.812zm7.44 5.252a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"/>
            </svg>
            Verified
          </span>
        </div>

        <!-- Top Right: Price Badge -->
        <div class="absolute top-3 right-3">
          <span class="px-3 py-1.5 text-sm font-bold bg-white text-gray-900 rounded-full shadow-lg">
            {{ room.price | currencyCompact }}/mo
          </span>
        </div>

        <!-- Heart Icon (Top Right Corner) -->
        <button 
          class="absolute top-3 right-3 mt-10 w-9 h-9 bg-white rounded-full shadow-md flex items-center justify-center hover:bg-gray-50 transition-colors"
          (click)="toggleSave($event)"
          [attr.aria-label]="isSaved() ? 'Unsave listing' : 'Save listing'"
        >
          <svg class="w-5 h-5" [class.text-red-500]="isSaved()" [class.fill-current]="isSaved()" [class.text-gray-600]="!isSaved()" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"/>
          </svg>
        </button>
      </div>

      <!-- Content -->
      <div class="p-4">
        <!-- Auto-Generated Title -->
        <h3 class="font-semibold text-base text-gray-900 mb-3 group-hover:text-brand-primary transition-colors">
          {{ getAutoGeneratedTitle() }}
        </h3>

        <!-- Posted By Section -->
        <div class="flex items-center gap-2">
          <img
            [src]="getHostAvatar()"
            [alt]="room.hostName || 'Host'"
            class="w-8 h-8 rounded-full object-cover border border-gray-200"
          >
          <div class="flex items-center gap-2 text-sm">
            <span class="text-gray-700 font-medium">{{ room.hostName || 'Anonymous' }}</span>
            <span class="text-gray-400">•</span>
            <div class="flex items-center gap-1">
              <span class="w-2 h-2 bg-green-500 rounded-full"></span>
              <span class="text-gray-500 text-xs">Online</span>
            </div>
          </div>
        </div>
      </div>
    </article>
  `,
  styles: [`
    .img-loading {
      opacity: 0.5;
    }
  `]
})
export class RoomCardComponent {
  @Input({ required: true }) room!: RoomCard;
  imgLoading = true;
  private savedState = signal(false);

  constructor(private router: Router) {}

  ngOnInit() {
    this.savedState.set(this.room.saved || false);
  }

  /**
   * Auto-generate title based on room type and location
   * Priority: University > City
   */
  getAutoGeneratedTitle(): string {
    const roomType = this.getRoomTypeLabel();
    
    // If university is available, use it
    if (this.room.universityName) {
      return `${roomType} near ${this.room.universityName}`;
    }
    
    // Otherwise use city
    if (this.room.city) {
      return `${roomType} in ${this.room.city}`;
    }
    
    // Fallback to room type only
    return `${roomType} Available`;
  }

  /**
   * Get formatted room type label
   */
  getRoomTypeLabel(): string {
    const type = this.room.roomType || this.room.type || 'Room';
    // Capitalize first letter
    return type.charAt(0).toUpperCase() + type.slice(1).toLowerCase() + ' Room';
  }

  /**
   * Get host avatar with fallback
   */
  getHostAvatar(): string {
    // Check if there's a host photo in the room data
    if (this.room.photos && this.room.photos.length > 1) {
      return this.room.photos[1]; // Assuming second photo might be host photo
    }
    // Use a default avatar based on hostId or hostName
    const seed = this.room.hostId || this.room.hostName || 'default';
    return `https://api.dicebear.com/7.x/avataaars/svg?seed=${seed}`;
  }

  isSaved(): boolean {
    return this.savedState();
  }

  toggleSave(event: Event): void {
    event.stopPropagation();
    this.savedState.set(!this.savedState());
    // TODO: Call API to save/unsave
  }

  navigateToDetail(): void {
    this.router.navigate(['/listing', this.room.id]);
  }

  onImgLoad(): void {
    this.imgLoading = false;
  }
}
